baseURL = "http://ptrsports.com"
languageCode = "en-us"
title = "PTR Sports"
theme = "ananke"
sectionPagesMenu = "main"

[[menu.main]]
    name = "Services"
    weight = 1
    identifier = "services"
    url = "/services/"
[[menu.main]]
    name = "Meet the Experts"
    weight = 2
    identifier = "meet"
    url = "/meet/"
[[menu.main]]
    name = "For Patients"
    weight = 3
    identifier = "for_patients"
    url = "/patients/"

[[menu.main]]
    name = "FAQs"
    weight = 4
    identifier = "faqs"
    url = "/faqs"
